services:
  waltuh:
    build:
      context: ./WaltuhGame
      dockerfile: Dockerfile
    volumes:
      - ./build:/app/build
    command: gunicorn -w 1 -b 0.0.0.0:8000 app:app 
    networks:
      - site_network

networks:
  site_network:
    external: true

