services:
  server:
    container_name: waltuh-game
    build:
      context: ./WaltuhGame
    volumes:
      - ./build:/app/build
    command: gunicorn -w 1 -b 0.0.0.0:8000 app:app 

  cloudflared:
    restart: unless-stopped
    image: cloudflare/cloudflared:latest
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
